version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=only
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
    depends_on:
      - db
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: only
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d only"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dbdata: